sudo: false
language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://github.com/CommBank/ci.git
- chmod ugo+x ci/*
- ci/sbt-setup.sh
- ci/sbt-setup-version.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; project core; set fork in Test :=
  false; test; project test; set fork in Test := false; test; project all; package;
  project example; set fork in Test := false; test; assembly; project tools; set fork
  in Test := false; set parallelExecution in Test := false; set logBuffered := false;
  test; assembly' && ci/sbt-deploy.sh && ci/sbt-gh-pages-ssh.sh
after_script:
- rm -rf ci
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/1befda9a908413f84c55
    on_success: always
    on_failure: always
    on_start: false
env:
  global:
    secure: a5+AtXTDCwd0moeDso1s8t1TR3yxFWdzEjvUWjYNGcxqg75c7UvBEihDPmIcVEvmTqHURYV2Zf96d4c8QMLz2ENorRNwlOF8zZi7wnesUwD0s4lHLNqXsc8mlfmT2hPxTNBzG7BLeLWol05RSJmJyIr9s/EscrWP2sdV9QEee6c=
before_install:
- openssl aes-256-cbc -K $encrypted_0f538816d8b4_key -iv $encrypted_0f538816d8b4_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key.pem -d
